### ISSUE TITLE
Invalid site key error using reCaptcha v3

### ISSUE THREAD

**Issue by joeyramone76** [andrewlimaza/caldera-forms-anti-spam#16]
Hi,
 using reCaptcha v3 we have an error in the javascript console:

> recaptcha__en.js:519 Uncaught Error: Invalid site key or not loaded in api.js: xxxxxxxxxxxxx
But I've checked the site key and it's the same the the error message show.

**Comment by andrewlimaza** [comment]
Can you please ensure you're using a V3 key? Please can you generate a new key and let me know if this helps.

**Comment by andrewlimaza** [comment]
If you're still experiencing issues with this, please feel free to open another issue.
