### ISSUE TITLE
Regarding anti spam and Caldera Forms

### ISSUE THREAD

**Issue by paaljoachim** [andrewlimaza/caldera-forms-anti-spam#9]
Hi

I am curious what measures there are in Caldera Forms in regards to removing/avoiding e-mails that contain spam?

As I have noticed one of my client sites have lately received a lot of spam e-mails.

Thanks.

**Comment by andrewlimaza** [comment]
Hey @paaljoachim 

This plugin is an extension of Caldera Forms and currently only supports Google reCAPTCHA and add's it as a field type.

I'd recommend in reaching out to Caldera Forms directly to find out about their built-in anti-spam features.
